name: Indian Market Live Update

on:
  schedule:
    # IST 9:15 AM to 3:30 PM (Mon-Fri)
    - cron: '*/15 3-10 * * 1-5'
  workflow_dispatch: # मैनुअल रन बटन के लिए

jobs:
  update-market:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
            - name: Install Libs
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt



      - name: Run Market Engine
        env:
          # अगर आपने GitHub Secrets में टोकन डाला है तो इसे इस्तेमाल करें
          PUSHBULLET_TOKEN: ${{ secrets.PUSHBULLET_TOKEN }}
        run: python main.py

