name: Market Signal Bot

on:
  schedule:
    - cron: '*/15 * * * *' # हर 15 मिनट में चलेगा
  workflow_dispatch: # मैन्युअल चलाने के लिए

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Signal Script
        run: python main.py
