name: Market Signal Bot
on:
  schedule:
    - cron: '*/5 * * * *' # Har 5 minute mein chalega
  workflow_dispatch:      # Manual button ke liye

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install pyrebase4 requests

      - name: Run Bot
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          UPSTOX_ACCESS_TOKEN: ${{ secrets.UPSTOX_ACCESS_TOKEN }}
        run: python main.py



