name: Auto Update
on:
  schedule: [{cron: "*/10 * * * *"}]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - setup-python: {python-version: '3.9'}
      - run: pip install yfinance pandas pandas_ta
      - run: python dashboard.py
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git add data.json
          git commit -m "Auto Update" || exit 0
          git push
