name: Auto Update
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install yfinance pandas pandas_ta
      - name: Run update script
        run: python dashboard.py
      - name: Commit and push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data.json
          git commit -m "Auto update data" || exit 0
          git push
